<?php
$_lang['import'] = 'Import';
$_lang['imports'] = 'Imports';
$_lang['imports.desc'] = 'Manage your imports here.';
$_lang['imports.description'] = 'Description';
$_lang['imports.import_err_ae'] = 'A import with that name already exists.';
$_lang['imports.import_err_nf'] = 'import not found.';
$_lang['imports.import_err_ns'] = 'import not specified.';
$_lang['imports.import_err_ns_name'] = 'Please specify a name for the import.';
$_lang['imports.import_err_remove'] = 'An error occurred while trying to remove the import.';
$_lang['imports.import_err_save'] = 'An error occurred while trying to save the import.';
$_lang['imports.import_create'] = 'Create New import';
$_lang['imports.import_remove'] = 'Remove import';
$_lang['imports.import_remove_confirm'] = 'Are you sure you want to remove this import?';
$_lang['imports.import_update'] = 'Update import';
$_lang['imports.downloads'] = 'Downloads';
$_lang['imports.location'] = 'Location';
$_lang['imports.management'] = 'imports Management';
$_lang['imports.management_desc'] = 'Manage your imports here. You can edit them by either double-clicking on the grid or right-clicking on the respective row.';
$_lang['imports.name'] = 'Name';
$_lang['imports.search...'] = 'Search...';
$_lang['imports.top_downloaded'] = 'Top Downloaded imports';
$_lang['imports.season'] = 'Season';
$_lang['imports.league'] = 'League';
$_lang['imports.round'] = 'Round';
$_lang['imports.game'] = 'Game';
$_lang['imports.resourceID'] = 'ResourceID';

$_lang['imports.createdon'] = 'created on';